"product_id","name","category_id","category_name"
1,"Laptop",1,"Electronics"
2,"Smartphone",1,"Electronics"
3,"Tablet",1,"Electronics"
4,"Bluetooth Speaker",1,"Electronics"
5,"Fiction Book",2,"Books"
6,"Cookbook",2,"Books"
7,"T-shirt",3,"Clothing"
8,"Jeans",3,"Clothing"
9,"Blender",4,"Home & Kitchen"
10,"Coffee Maker",4,"Home & Kitchen"
11,"Toy Car",5,"Toys"
12,"Doll",5,"Toys"
13,"Board Game",5,"Toys"
14,"Monitor",1,"Electronics"
15,"Headphones",1,"Electronics"
